#
# Makefile for the pNFS Objects Layout Driver kernel module
#
objlayoutdriver-y := pnfs_osd_xdr_cli.o objlayout.o objio_osd.o
obj-$(CONFIG_PNFS_OBJLAYOUT) += objlayoutdriver.o

#
# Panasas pNFS Layout Driver kernel module
#
panlayoutdriver-y := pnfs_osd_xdr_cli.o objlayout.o panfs_shim.o
obj-$(CONFIG_PNFS_PANLAYOUT) += panlayoutdriver.o
